### ISSUE TITLE
Error when exporting : export() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by pulse-mind** [django-import-export/django-import-export#1352]
Hello,

**Describe the bug**
I am exporting an item to xlsx and I get an error

```
[21/11/2021 18:32:33] Internal Server Error: /app/projecta/itemproduct/export/
Traceback (most recent call last):
  File "D:\Perso\VirtualEnv\projecta\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Perso\VirtualEnv\projecta\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Perso\VirtualEnv\projecta\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Perso\VirtualEnv\projecta\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Perso\VirtualEnv\projecta\lib\site-packages\django\contrib\admin\sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "D:\Perso\VirtualEnv\projecta\lib\site-packages\import_export\admin.py", line 415, in export_action
    export_data = self.get_export_data(file_format, queryset, request=request, encoding=self.to_encoding)
  File "D:\Perso\VirtualEnv\projecta\lib\site-packages\import_export\admin.py", line 390, in get_export_data
    data = self.get_data_for_export(request, queryset, *args, **kwargs)
  File "D:\Perso\VirtualEnv\projecta\lib\site-packages\import_export\mixins.py", line 61, in get_data_for_export
    return resource_class(**self.get_export_resource_kwargs(request, *args, **kwargs))\
TypeError: export() got an unexpected keyword argument 'encoding'
```
It is working fine with django-import-export==2.5.0

**Versions (please complete the following information):**
 - django-import-export==2.6.1
 - Python 3.8
 - Django 3.2.9

Thank you for all the job done!!

**Comment by matthewhegarty** [comment]
Hi - thanks for reporting this.  I'm not able to reproduce it using the example application in 2.6.1, but maybe I am missing something.  Is it possible you have defined a Resource which overrides `export()`?

Are you able to reproduce this using the example application?

**Comment by pulse-mind** [comment]
Hi thank you for your answer

Yes I have some overrides like this 

```
class CustomerResource(resources.ModelResource):
    ...
    def export(self, queryset=None):
    ...
```

**Comment by matthewhegarty** [comment]
If you can rename your overridden `export()` to match the method definition, it should work:

```
    def export(self, queryset=None, *args, **kwargs):
```

**Comment by pulse-mind** [comment]
Hello,
I've done the test today and it works fine. 
Thank you for your help!!!!
