### ISSUE TITLE
setup_admin_integration.<locals>.display_for_field) got an unexpected keyword argument 'avoid _link'

### ISSUE THREAD

**Issue by JV-conseil** [django-import-export/django-import-export#2054]
**Describe the bug**

```txt
TypeError at /admin/
setup_admin_integration.<locals>.display_for_field) got an unexpected keyword argument 'avoid _link'
```

```html
.../lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py, line 246, in items_for_result
{% result_list cl %}
```

**To Reproduce**

1. Go to ` /admin/`
2. See error

**Versions (please complete the following information):**

 - Django Import Export: 4.3.7
 - Python: 3.12.10
 - Django: 5.2

**Expected behavior**

Load targeted admin page.

**Screenshots**

![setup_admin_integration.<locals>.display_for_field() got an unexpected keyword argument 'avoid_link'](https://github.com/user-attachments/assets/41cc8b7a-2d49-4bf6-89e4-a33d25b9bb71)

**Additional context**

**Comment by nithinvas** [comment]
I came accross the same issue

attaching the code snippet from the file that is causing the issue : django/contrib/admin/templatetags/admin_list.py in items_for_result at line 246

                    if field_val is None:
                        result_repr = empty_value_display
                    else:
                        result_repr = field_val
                else:
                    result_repr = display_for_field(
                        value,
                        f,
                        empty_value_display,
                        avoid_link=link_to_changelist,
                    )

**Comment by matthew-pest** [comment]
I ran into the same issue...

Upgrading a few packages fixed it for me. Took hours to figure this out :/

django-money 3.5.2 -> 3.5.4 (known issue that 3.5.4 fixed)

This helped:
https://github.com/django-money/django-money/commit/e6e33913cd07ecd7f59744cb00e1f29c6353df1a

I upgraded a few other old package versions to get everything working with Django 5.2.1 - I just got this all sorted myself and wanted to share ASAP!

**Comment by matthew-pest** [comment]
![Image](https://github.com/user-attachments/assets/14bc3423-5af5-4124-8055-2e8d40ec75df)

**Comment by JV-conseil** [comment]
I can report the problem has been fixed on my side with no code modification ✅

Maybe updating [django-money](https://github.com/django-import-export/django-import-export/issues/2054#issuecomment-2877118674) has signalled by @matthew-pest played a positive role 🤷
