### ISSUE TITLE
Export error: "TypeError: __init__() missing 1 required positional argument: 'sortable_by'"

### ISSUE THREAD

**Issue by delabania** [django-import-export/django-import-export#823]
In Django 2.1 django.contrib.admin.views.main ChangeList class takes in __init__ sortable_by argument, which is not passed in admin.py at 372 line (it's compatible with previous versions of Django, where there is no sortable_by param in Django's ChangeList). 
Can you prepare version working with Django 2.1?

**Comment by msrshahrukh100** [comment]
yes i am facing this issue as well, any solution to this?

**Comment by m-strzelczyk** [comment]
It seems it has been fixed by 54232db4a511cc5f0b085c6bb192c3619f27e452, but this version is still not released to PyPi. @bmihelac can you please push this change to PyPi?

**Comment by msrshahrukh100** [comment]
@bmihelac can we have it released, please. It is urgently required for a website working for relief work in flood-hit Kerala, India.

**Comment by bmihelac** [comment]
Hi @msrshahrukh100, sorry to hear that. Until there is new release, you can install development version with:

```
pip install -e git+https://github.com/django-import-export/django-import-export.git#egg=django-import-export
```

docs:
https://django-import-export.readthedocs.io/en/latest/installation.html#installation-and-configuration

**Comment by msrshahrukh100** [comment]
@bmihelac thanks a lot

**Comment by logicappsource** [comment]
Any updates this freaking sucks ????!?!?!

**Comment by tiholic** [comment]
This issue seems to be fixed in 1.1.0
