### ISSUE TITLE
Error when trying to open export windows with import_export 3.3.4

### ISSUE THREAD

**Issue by Ymil** [django-import-export/django-import-export#1716]
**Describe the bug**
Error when trying to open export windows with import_export 3.3.4

**To Reproduce**
1. Go to 'admin model section'
2. Click on 'export'

**Versions (please complete the following information):**
 - Django Import Export: 3.3.4
 - Python 3.8.12
 - Django 3.2.14

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**

**Error message:**

```
TypeError __init__() got an unexpected keyword argument 'model'
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/venv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/venv/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/venv/lib/python3.8/site-packages/import_export/admin.py", line 836, in export_action
    context["fields_list"] = [
  File "/venv/lib/python3.8/site-packages/import_export/admin.py", line 841, in <listcomp>
    for field in res(model=self.model).get_user_visible_fields()
TypeError: __init__() got an unexpected keyword argument 'model'
```

I see that this problem is introduction in this PR https://github.com/django-import-export/django-import-export/pull/1685/files
Maybe, this is related to the older version of Django, I see that the code for the construction fields in `import_action` and `export_actions` are different and I'm not sure if it's okay or if it's better to normal.

Version 3.3.2 works fine.

**Comment by matthewhegarty** [comment]
I couldn't reproduce this using the import-export example app.  Can you reproduce with the [example app](https://django-import-export.readthedocs.io/en/latest/installation.html#example-app)?  Does it still occur if you upgrade to Django 4.2? (3.2 is unsupported from [April](https://endoflife.date/django)).

**Comment by jlicht** [comment]
I experienced this error after upgrading from 3.3.3 to 3.3.6

Django: 4.2.9
Python: 3.10.3

**Comment by jlicht** [comment]
This is the Resource that's causing the problem. It's a base class from which other resources inherit.

```
class PIIModelResource(resources.ModelResource):
    def __init__(self, user):
        self.user = user

    def export(self, queryset=None, *args, **kwargs):
        if self.user.has_perm("core.view_person"):
            return super().export(queryset, *args, **kwargs)
        else:
            raise ValidationError("You do not have permission to export this information")
```

**Comment by jlicht** [comment]
This fixed it, thanks!

```python
    def __init__(self, user=None, model=None):
        super().__init__(model=model)
        self.user = user
```
